# this takes exponential time unless _flatten_object_list uses a worklist
project('repeated objects', 'c')
l0 = static_library('l0', 'src.c', install: true)
l1 = static_library('l1', objects: [l0.extract_all_objects(recursive: true), l0.extract_all_objects(recursive: true)])
l2 = static_library('l2', objects: [l1.extract_all_objects(recursive: true), l1.extract_all_objects(recursive: true)])
l3 = static_library('l3', objects: [l2.extract_all_objects(recursive: true), l2.extract_all_objects(recursive: true)])
l4 = static_library('l4', objects: [l3.extract_all_objects(recursive: true), l3.extract_all_objects(recursive: true)])
l5 = static_library('l5', objects: [l4.extract_all_objects(recursive: true), l4.extract_all_objects(recursive: true)])
l6 = static_library('l6', objects: [l5.extract_all_objects(recursive: true), l5.extract_all_objects(recursive: true)])
l7 = static_library('l7', objects: [l6.extract_all_objects(recursive: true), l6.extract_all_objects(recursive: true)])
l8 = static_library('l8', objects: [l7.extract_all_objects(recursive: true), l7.extract_all_objects(recursive: true)])
l9 = static_library('l9', objects: [l8.extract_all_objects(recursive: true), l8.extract_all_objects(recursive: true)])
l10 = static_library('l10', objects: [l9.extract_all_objects(recursive: true), l9.extract_all_objects(recursive: true)])
l11 = static_library('l11', objects: [l10.extract_all_objects(recursive: true), l10.extract_all_objects(recursive: true)])
l12 = static_library('l12', objects: [l11.extract_all_objects(recursive: true), l11.extract_all_objects(recursive: true)])
l13 = static_library('l13', objects: [l12.extract_all_objects(recursive: true), l12.extract_all_objects(recursive: true)])
l14 = static_library('l14', objects: [l13.extract_all_objects(recursive: true), l13.extract_all_objects(recursive: true)])
l15 = static_library('l15', objects: [l14.extract_all_objects(recursive: true), l14.extract_all_objects(recursive: true)])
l16 = static_library('l16', objects: [l15.extract_all_objects(recursive: true), l15.extract_all_objects(recursive: true)])
l17 = static_library('l17', objects: [l16.extract_all_objects(recursive: true), l16.extract_all_objects(recursive: true)])
l18 = static_library('l18', objects: [l17.extract_all_objects(recursive: true), l17.extract_all_objects(recursive: true)])
l19 = static_library('l19', objects: [l18.extract_all_objects(recursive: true), l18.extract_all_objects(recursive: true)])
