.TH MESONCONF "1" "December 2017" "mesonconf 0.44.0" "User Commands"
.SH NAME
mesonconf - a tool to configure Meson builds
.SH DESCRIPTION

This executable is deprecated and will be removed in the future. The
functionality that was in this executable can be invoked via the main Meson
command like this:

.B meson configure <options>
