.TH MESON "1" "December 2017" "meson 0.44.0" "User Commands"
.SH NAME
mesontest - test tool for the Meson build system
.SH DESCRIPTION

This executable is deprecated and will be removed in the future. The
functionality that was in this executable can be invoked via the main Meson
command like this:

.B meson test <options>

.SH SEE ALSO
http://mesonbuild.com/
