.TH MESON "1" "February 2013" "meson 0.1.0" "User Commands"
.SH NAME
meson - an experimental build system
.SH DESCRIPTION
usage: meson [options] [source directory] [build directory]
.SS "options:"
.TP
\fB\-\-version\fR
print version number
.TP
\fB\-\-help\fR
print command line help
.SH SEE ALSO
https://sourceforge.net/p/meson
