.TH MESONGUI "1" "April 2016" "mesongui 0.31.0" "User Commands"
.SH NAME
mesongui - a gui for the Meson build system
.SH DESCRIPTION

Mesongui provides a graphical user interface to the Meson
build system. It can be used for two main purposes: configuring
an existing build or creating a new build for the given source.

.B mesongui [
.I source or build directory
.B ]

If the argument is a directory with a Meson project, the
Gui will allow you to configure and generate a build tree
for it.

If the argument is an existing build directory, Mesongui will
start a gui that will show all your configuration
options and allows you to change them as desired. The
gui can also be used to build and install the project.

.SH SEE ALSO
http://mesonbuild.com/
