.TH MESONINTROSPECT "1" "December 2017" "mesonintrospect 0.44.0" "User Commands"
.SH NAME
mesonintrospect - a tool to extract information about a Meson build
.SH DESCRIPTION

This executable is deprecated and will be removed in the future. The
functionality that was in this executable can be invoked via the main Meson
command like this:

.B meson introspect <options>

.SH SEE ALSO
http://mesonbuild.com/
