.TH WRAPTOOL "1" "December 2017" "meson 0.44.0" "User Commands"
.SH NAME
wraptool - source dependency downloader
.SH DESCRIPTION

This executable is deprecated and will be removed in the future. The
functionality that was in this executable can be invoked via the main Meson
command like this:

.B meson wrap <options>

.SH SEE ALSO
http://wrapdb.mesonbuild.com/
