project('t', 'c')
pkg = import('pkgconfig')
l0 = static_library('l0', 'x0.c', install: true)
l1 = static_library('l1', 'x1.c', link_with: l0, install: true)
l2 = static_library('l2', 'x2.c', link_with: [l1, l0], install: true)
l3 = static_library('l3', 'x3.c', link_with: [l2, l1], install: true)
l4 = static_library('l4', 'x4.c', link_with: [l3, l2], install: true)
l5 = static_library('l5', 'x5.c', link_with: [l4, l3], install: true)
l6 = static_library('l6', 'x6.c', link_with: [l5, l4], install: true)
l7 = static_library('l7', 'x7.c', link_with: [l6, l5], install: true)
l8 = static_library('l8', 'x8.c', link_with: [l7, l6], install: true)
l9 = static_library('l9', 'x9.c', link_with: [l8, l7], install: true)
l10 = static_library('l10', 'x10.c', link_with: [l9, l8], install: true)
l11 = static_library('l11', 'x11.c', link_with: [l10, l9], install: true)
l12 = static_library('l12', 'x12.c', link_with: [l11, l10], install: true)
l13 = static_library('l13', 'x13.c', link_with: [l12, l11], install: true)
l14 = static_library('l14', 'x14.c', link_with: [l13, l12], install: true)
l15 = static_library('l15', 'x15.c', link_with: [l14, l13], install: true)
l16 = static_library('l16', 'x16.c', link_with: [l15, l14], install: true)
l17 = static_library('l17', 'x17.c', link_with: [l16, l15], install: true)
l18 = static_library('l18', 'x18.c', link_with: [l17, l16], install: true)
l19 = static_library('l19', 'x19.c', link_with: [l18, l17], install: true)
l20 = static_library('l20', 'x20.c', link_with: [l19, l18], install: true)
l21 = static_library('l21', 'x21.c', link_with: [l20, l19], install: true)
l22 = static_library('l22', 'x22.c', link_with: [l21, l20], install: true)
pkg.generate(l22, filebase: 'top')
