#define __STRINGIFY(x) #x
#define TEST_STRINGIFY(x) __STRINGIFY(x)

#define TEST_VERSION_MAJOR 6
#define TEST_VERSION_MINOR 0
#define TEST_VERSION_BUGFIX 0

#define TEST_VERSION_STR             \
  TEST_STRINGIFY(TEST_VERSION_MAJOR) \
  "." TEST_STRINGIFY(TEST_VERSION_MINOR) "." TEST_STRINGIFY(TEST_VERSION_BUGFIX)

// TEST_VERSION_STR "6" "." "0" "." "0"
