[mypy]
strict_optional               = False
show_error_context            = False
show_column_numbers           = True
ignore_missing_imports        = False
implicit_reexport             = False

follow_imports                = silent
warn_redundant_casts          = True
warn_unused_ignores           = True
warn_return_any               = True
# warn_unreachable            = True
disallow_untyped_calls        = True
disallow_untyped_defs         = True
disallow_incomplete_defs      = True
disallow_untyped_decorators   = True
no_implicit_optional          = True
strict_equality               = True
check_untyped_defs            = True
# disallow_any_expr           = True
# disallow_any_decorated      = True
# disallow_any_explicit       = True
# disallow_any_generics       = True
# disallow_subclassing_any    = True

# future default behaviors
allow_redefinition_new        = True
local_partial_types           = True

[mypy-mesonbuild.*]
strict_optional               = True

[mypy-mesonbuild.ast.interpreter]
strict_optional               = False

[mypy-mesonbuild.ast.introspection]
strict_optional               = False

[mypy-mesonbuild.backend.backends]
strict_optional               = False

[mypy-mesonbuild.backend.ninjabackend]
strict_optional               = False

[mypy-mesonbuild.backend.nonebackend]
strict_optional               = False

[mypy-mesonbuild.backend.vs2010backend]
strict_optional               = False

[mypy-mesonbuild.backend.xcodebackend]
strict_optional               = False

[mypy-mesonbuild.build]
strict_optional               = False

[mypy-mesonbuild.cargo.interpreter]
strict_optional               = False

[mypy-mesonbuild.cmake.executor]
strict_optional               = False

[mypy-mesonbuild.cmake.interpreter]
strict_optional               = False

[mypy-mesonbuild.cmake.toolchain]
strict_optional               = False

[mypy-mesonbuild.cmake.tracetargets]
strict_optional               = False

[mypy-mesonbuild.compilers.*]
strict_optional               = False

[mypy-mesonbuild.dependencies.base]
strict_optional               = False

[mypy-mesonbuild.dependencies.boost]
strict_optional               = False

[mypy-mesonbuild.dependencies.configtool]
strict_optional               = False

[mypy-mesonbuild.dependencies.cuda]
strict_optional               = False

[mypy-mesonbuild.dependencies.detect]
strict_optional               = False

[mypy-mesonbuild.dependencies.dev]
strict_optional               = False

[mypy-mesonbuild.dependencies.dub]
strict_optional               = False

[mypy-mesonbuild.dependencies.framework]
strict_optional               = False

[mypy-mesonbuild.dependencies.hdf5]
strict_optional               = False

[mypy-mesonbuild.dependencies.misc]
strict_optional               = False

[mypy-mesonbuild.dependencies.mpi]
strict_optional               = False

[mypy-mesonbuild.dependencies.pkgconfig]
strict_optional               = False

[mypy-mesonbuild.dependencies.python]
strict_optional               = False

[mypy-mesonbuild.dependencies.qt]
strict_optional               = False

[mypy-mesonbuild.dependencies.ui]
strict_optional               = False

[mypy-mesonbuild.interpreterbase.interpreterbase]
strict_optional               = False

[mypy-mesonbuild.interpreterbase.baseobjects]
strict_optional               = False

[mypy-mesonbuild.interpreterbase.decorators]
strict_optional               = False

[mypy-mesonbuild.interpreter.interpreter]
strict_optional               = False

[mypy-mesonbuild.interpreter.interpreterobjects]
strict_optional               = False

[mypy-mesonbuild.interpreter.compiler]
strict_optional               = False

[mypy-mesonbuild.interpreter.dependencyfallbacks]
strict_optional               = False

[mypy-mesonbuild.linkers.detect]
strict_optional               = False

[mypy-mesonbuild.mformat]
strict_optional               = False

[mypy-mesonbuild.mintro]
strict_optional               = False

[mypy-mesonbuild.modules]
strict_optional               = False

[mypy-mesonbuild.modules.cmake]
strict_optional               = False

[mypy-mesonbuild.modules.codegen]
strict_optional               = False

[mypy-mesonbuild.modules.cuda]
strict_optional               = False

[mypy-mesonbuild.modules.gnome]
strict_optional               = False

[mypy-mesonbuild.modules.rust]
strict_optional               = False

[mypy-mesonbuild.modules.pkgconfig]
strict_optional               = False

[mypy-mesonbuild.modules.python]
strict_optional               = False

[mypy-mesonbuild.modules._qt]
strict_optional               = False

[mypy-mesonbuild.modules.i18n]
strict_optional               = False

[mypy-mesonbuild.mparser]
strict_optional               = False

[mypy-mesonbuild.msetup]
strict_optional               = False

[mypy-mesonbuild.msubprojects]
strict_optional               = False

[mypy-mesonbuild.mtest]
strict_optional               = False

[mypy-mesonbuild.optinterpreter]
strict_optional               = False

[mypy-mesonbuild.options]
strict_optional               = False

[mypy-mesonbuild.rewriter]
strict_optional               = False

[mypy-mesonbuild.wrap.wrap]
strict_optional               = False

[mypy-mesonbuild.wrap.wraptool]
strict_optional               = False

[mypy-mesonbuild.scripts.coverage]
strict_optional               = False

[mypy-mesonbuild.scripts.symbolextractor]
strict_optional               = False

[mypy-mesonbuild.scripts.scanbuild]
strict_optional               = False

[mypy-mesonbuild.scripts.depfixer]
strict_optional               = False

[mypy-mesonbuild.utils.universal]
strict_optional               = False
