[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.ruff]
  line-length = 100
  target-version = "py310"

  [tool.ruff.lint]
    select = ["E", "F", "I", "PLE", "UP"]

    exclude = [
      "test cases/**",
    ]

    ignore = [
      "E501",  # line-too-long. Worth fixing. Also, there's like 4000 violations
      "E741",  # Ambiguous variable. Might be worth fixing, but doesn't like one letter variables in short loops
    ]
