[package]
name = 'sub'
version = '1'

[build-dependencies]
system-deps = "6"

[lib]
name = "sub"
path = "lib.rs"

[package.metadata.system-deps]
glib = { name = "glib-2.0", version=" 2.0 , 2.1 , <3 ", feature="default" }
gobject = { name = "gobject-2.0", version=">=99", optional=true }
notfound = { feature="notfound" }
libffi = "1.0"
