/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:   gcc -c  -w -g3 -O0  -I/home/bartoc/Source/nim/lib -o '/home/bartoc/Source/meson/test cases/nim/1 basic/nimcache/prog.o' '/home/bartoc/Source/meson/test cases/nim/1 basic/nimcache/prog.c' */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;typedef struct TGenericSeq TGenericSeq;struct TGenericSeq {NI len;NI reserved;};
struct NimStringDesc {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
#line 408 "/home/bartoc/Source/nim/lib/system/sysio.nim"
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
#line 2872 "/home/bartoc/Source/nim/lib/system.nim"
static N_INLINE(void, initStackBottomWith)(void* locals);
#line 227 "/home/bartoc/Source/nim/lib/system/gc_common.nim"
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
#line 405 "/home/bartoc/Source/nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s);
#line 400 "/home/bartoc/Source/nim/lib/system/excpt.nim"
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
#line 70 "/home/bartoc/Source/nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void);NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, progDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;STRING_LITERAL(TM_3gsRviFqqgOPGusKWyM6fw_3, "The nim compiler is working", 27);NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_3gsRviFqqgOPGusKWyM6fw_2 = {((NimStringDesc*) &TM_3gsRviFqqgOPGusKWyM6fw_3)};

#line 2872 "/home/bartoc/Source/nim/lib/system.nim"
static N_INLINE(void, initStackBottomWith)(void* locals) {

#line 2876 "/home/bartoc/Source/nim/lib/system.nim"
	setStackBottom(locals);}
void PreMainInner(void) {
	systemInit000();
	progDatInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}



#line 405 "/home/bartoc/Source/nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
#line 406 "/home/bartoc/Source/nim/lib/system/excpt.nim"
	T1_ = (NI)0;
#line 406 "/home/bartoc/Source/nim/lib/system/excpt.nim"
	{
#line 406 "/home/bartoc/Source/nim/lib/system/excpt.nim"
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;		T1_ = ((NI) 0);	}	goto LA2_;	LA4_: ;	{
#line 406 "/home/bartoc/Source/nim/lib/system/excpt.nim"
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));	}	LA2_: ;	(*s).calldepth = ((NI16) (T1_));
#line 407 "/home/bartoc/Source/nim/lib/system/excpt.nim"
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 408 "/home/bartoc/Source/nim/lib/system/excpt.nim"
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 409 "/home/bartoc/Source/nim/lib/system/excpt.nim"
	{
#line 409 "/home/bartoc/Source/nim/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
#line 409 "/home/bartoc/Source/nim/lib/system/excpt.nim"
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();	}	LA9_: ;}


#line 70 "/home/bartoc/Source/nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 71 "/home/bartoc/Source/nim/lib/system/excpt.nim"
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("prog", "prog.nim");
#line 1 "/home/bartoc/Source/meson/test cases/nim/1 basic/prog.nim"
	nimln_(1, "prog.nim");	echoBinSafe(TM_3gsRviFqqgOPGusKWyM6fw_2, 1);	popFrame();}

NIM_EXTERNC N_NOINLINE(void, progDatInit000)(void) {
}

