# Copyright 2026 The Meson Development Team
# SPDX-License-Identifier: Apache-2.0
[project]
project_name = 'fuchsia_mesa3d'
build_system = 'bazel'

[copyright]
license_name = "fuchsia_license"
licenses = ["BSD-2-Clause"]
license_texts = ["LICENSE"]

[custom_target]
[custom_target.workarounds]
skip_export_include_dirs = [
    "gfxstream_guest_vk_autogen",
    "vulkan_gfxstream_header",
]

[[config]]
config_name = 'fuchsia_mesa3d_drivers'

[config.platforms]
host_platforms = ["fuchsia_x86_64"]
build_platforms = ["fuchsia_x86_64"]

[config.static_options]
glx = "disabled"
platforms = ""
gallium-drivers = ""
vulkan-drivers = 'gfxstream'
shader-cache = 'disabled'
opengl = false
egl = "disabled"
zlib = "disabled"
