# this test case can be deleted if support for unversioned python libs is removed

project('boost python test', 'cpp')

dependency('boost', modules: ['python', 'numpy'], required: true)
dependency('boost', modules: ['python3', 'numpy3'], required: true)
dependency('boost', modules: ['python313', 'numpy313'], required: true)
dependency('boost', modules: ['python314', 'numpy314'], required: true)
dependency('boost', modules: ['python315', 'numpy315'], required: true)
