name: cygwin

concurrency:
  group: cygwin-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      # Stable branches such as 0.56 or 1.0
      - '[0-9]+.[0-9]+'
    paths:
      - "mesonbuild/**"
      - "test cases/**"
      - "unittests/**"
      - ".github/workflows/cygwin.yml"
      - "run*tests.py"
  pull_request:
    paths:
      - "mesonbuild/**"
      - "test cases/**"
      - "unittests/**"
      - ".github/workflows/cygwin.yml"
      - "run*tests.py"

  # Try to ratchet circa forward weekly (every Sunday)
  schedule:
    - cron: '0 0 * * 0'
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  test:
    # do not run the weekly scheduled job in a fork
    #if: github.event_name != 'schedule' || github.repository == 'mesonbuild/meson'

    runs-on: windows-latest
    name: ${{ matrix.NAME }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - NAME: gccx64ninja
            ARCH: x86_64
    env:
      MESON_CI_JOBNAME: cygwin-${{ matrix.NAME }}
      GIST_ID: 3540b45017d28254b9b3805472340adf

    steps:
      # remove inheritable permissions since they break assumptions testsuite
      # makes about file modes
      - run: icacls . /inheritance:r /T /C

      - run: git config --global core.autocrlf input

      - uses: actions/checkout@v4

      - name: Find package cache dir
        id: package-cache
        run: |
          # rather than having to work this out here, cygwin-install-action
          # should simply take a package cache dir input.
          $workvol = Split-Path -Path "${{ runner.temp }}" -Qualifier
          echo "workvol=$workvol" >> $env:GITHUB_OUTPUT
        shell: powershell

      - uses: actions/cache/restore@v4
        with:
          path: ${{ steps.package-cache.outputs.workvol}}\cygwin-packages
          key: cygwin-packages-${{ github.run_number }}
          restore-keys: cygwin-packages-

      # determine the circa to use (N.B. it may be arch-specific)
      - name: Determine circa
        id: circa-select
        env:
          MODE: ${{github.event_name}}
        run: |
          if ( $env:MODE -eq 'schedule' ) {
            # if this is scheduled, use latest circa
            # (an empty site indicates to cygwin-install-action that is should use its default)
            $site = ""
            $checksig = "true"
            echo "Selecting latest circa"
          } else {
            # otherwise, fetch circa from the ratchet (updated below in 'schedule' mode)
            $gist = "https://gist.githubusercontent.com/jon-turney/$env:GIST_ID/raw/${{ matrix.ARCH }}"
            $response = Invoke-WebRequest -Uri "$gist" -UseBasicParsing
            $circa = $response.Content
            echo "Selecting circa $circa"
            # install cygwin from that circa using the time machine
            $site = "http://ctm.crouchingtigerhiddenfruitbat.org/pub/cygwin/circa/64bit/$circa"
            $checksig = "false"
          }
          echo "site=$site" >> $env:GITHUB_OUTPUT
          echo "checksig=$checksig" >> $env:GITHUB_OUTPUT
        shell: powershell

      - uses: cygwin/cygwin-install-action@v6
        id: install-action
        with:
          site: ${{ steps.circa-select.outputs.site }}
          check-sig: ${{ steps.circa-select.outputs.checksig }}
          platform: ${{ matrix.ARCH }}
          packages: |
            cmake
            gcc-fortran
            gcc-objc++
            gcc-objc
            git
            gobject-introspection
            gtk-doc
            libboost-devel
            libglib2.0-devel
            libgtk3-devel
            libxml2-devel
            libxslt-devel
            make
            ninja
            python2-devel
            python3-devel
            python3-libxml2
            python3-libxslt
            python3-gi
            python39-pip
            python39-wheel
            vala
            zlib-devel

      - uses: actions/cache/save@v4
        with:
          path: ${{ steps.install-action.outputs.package-cache }}
          key: cygwin-packages-${{ github.run_number }}

      - name: Find pip cache dir
        id: pip-cache
        run: |
          export PATH=/usr/bin:/usr/local/bin:$(cygpath ${SYSTEMROOT})/system32
          echo "dir=$(cygpath -wa $(python3 -m pip cache dir))" >> "$GITHUB_OUTPUT"
        shell: bash --noprofile --norc -o igncr -eo pipefail '{0}'

      - uses: actions/cache/restore@v4
        id: restore-cache
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: cygwin-pip-${{ github.run_number }}
          restore-keys: cygwin-pip-

      - name: Run pip
        run: |
          export PATH=/usr/bin:/usr/local/bin:$(cygpath ${SYSTEMROOT})/system32
          python3 -m pip --disable-pip-version-check install gcovr fastjsonschema pefile pytest pytest-subtests pytest-xdist
        shell: bash --noprofile --norc -o igncr -eo pipefail '{0}'

      - uses: actions/cache/save@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: cygwin-pip-${{ github.run_number }}

      - name: Run tests
        run: |
          export PATH=/usr/bin:/usr/local/bin:$(cygpath ${SYSTEMROOT})/system32
          python3 ./run_tests.py --backend=ninja
        env:
          # Cygwin's static boost installation is broken (some static library
          # variants such as boost_thread are not present)
          SKIP_STATIC_BOOST: 1
        shell: bash --noprofile --norc -o igncr -eo pipefail '{0}'

      # if this is a scheduled run, and it succeeded, update the circa
      - name: Update the circa ratchet
        run: |
          # get the circa from the cygwin installation at hand
          export CIRCA=$(date -d @$(cat /etc/setup/timestamp) +%Y/%m/%d/%H%M%S)
          # store it in the ratchet (by arch)
          curl --no-progress-meter -L \
            -X PATCH \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/gists/${GIST_ID} \
            --variable %ARCH \
            --variable %CIRCA \
            --expand-data '{"files":{"{{ARCH}}":{"content":"{{CIRCA}}"}}'
        if: (github.event_name == 'schedule')
        shell: bash --noprofile --norc -o igncr -eo pipefail '{0}'
        env:
          ARCH: ${{ matrix.ARCH }}
          # GitHub PAT with gist write permission
          GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.NAME }}
          path: meson-test-run.*
        # test log should be saved on failure
        if: ${{ !cancelled() }}
